### ISSUE TITLE
week 03 -day 02 - weather api

### ISSUE THREAD

**Issue by mdewey** [ejbee3/assignments#10]
# Cloudy with a chance of Syntax Error

Using a popular weather API, Create a web site that allows a user to search for a location and gets that location's weather.

## Objectives

- Practice working with an API
- Practice working with data that was structure by a third party

## Requirements

- Using `openweathermap.org`, create a simple UI that allows a user to search for the current weather by zip code or city.

### SIGN UP!

- [ ] Visit `openweathermap.org` and signup for an account
- [ ] Visit `API Keys` in your dashboard
- [ ] Copy your API key
- [ ] You can use the API key in any of the URLs by appending `appid=KEY`
  - Example: from the docs `https://api.openweathermap.org/data/2.5/weather?q=Tampa` becomes `https://api.openweathermap.org/data/2.5/weather?q=Tampa&appid=cbb5b6537cd4a6eccd9aee04ffffffff`
  - NOTE: It will take about 10 to 30 minutes for your API key to be active

### Explorer Mode

- [x] Create a simple HTML page that has a text box and a search `button`
- [x] Allow the user to type in a place, click the search button, and , using `openweathermap.org`, get the current weather for that location.
- [x] Display the weather to user by adding elements to the DOM.
- [ ] Allow the user to search by zip or city name.

### Adventure Mode

- [ ] Using the HTML5 Geolocation API, search for the users current location when page loads.
- [ ] Store the Users last search and use it to search for the value on page load. HINT: localstorage
- [ ] remove the need for the search button and search when the user stops typing. HINT: use setTimeout and the change event. to track when the user stops typing.

### Epic Mode

- [ ] Add a type a head using Google Places API
- [ ] Head back to Blackjack and use [this as your API](https://deckofcardsapi.com/).

**Comment by ejbee3** [comment]
Can't figure out how to display the data, will be the fetch data working though when I have the time

https://github.com/ejbee3/weather-api

**Comment by mdewey** [comment]
Great start, I would like to see you display the weather. Let me know if you want help doing that

**Comment by ejbee3** [comment]
https://github.com/ejbee3/weather-api

can display the weather using city name but still working on zip code function

**Comment by mdewey** [comment]
You are really close to getting this done. 

if you change 
``` 
 let cityOrZip = document.querySelector('#cityZip').value
  fetch('https://openweathermap.org/data/2.5/weather?q=Tampa' + apiKey)
``` 
to 
``` 
 let cityOrZip = document.querySelector('#cityZip').value
  fetch('https://openweathermap.org/data/2.5/weather?q='+cityOrZip + apiKey)
```

it should work.

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBXZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9ab12a6cb8616834a8b7e838629a5c8c61b5f7a3/giphy-14.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/79)**__

**Comment by mdewey** [comment]
Your homework was marked: **Acceptable**

![Not Bad](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--26e47afe0d88e75d27a696b1e3719f5c026a93c5/not-bad.gif)
> &ldquo;Not Bad&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/6)**__
