### ISSUE TITLE
career support - resumes - Build your Resume

### ISSUE THREAD

**Issue by ktrammell95** [ejbee3/assignments#21]
Key areas of Information to include:

## Contact information
- [x] Email
- [x] Phone Number (Google numbers are great if you want to protect your personal number)
- [x] Github link
- [x] Portfolio link

## Summary 
- [x]  Should be a brief paragraph (three to five sentences) that shows the value you bring by highlighting your skills and a couple of big career wins. But rather than labeling it a “summary,” simply use a headline that encapsulates your credentials.

## Skills 
- [x]  You’ll want to incorporate the right keywords so that your resume is optimized for application tracking systems

## Professional experience
- [x]  Focus on your accomplishments rather than your day-to-day responsibilities

## Education
- [x]  Simply write where you went college and your degree.
- [ ]  It’s ok to move this towards the top if you have limited work experience and want to highlight your experience at SDG

## Bonus:
- [x]  Volunteering and community service

## Due Date: Wednesday, June 19th
- [x]  Upload or submit a link to your resume for review.

**Comment by ejbee3** [comment]
https://docs.google.com/document/d/1y_1r-73PCC3A-V3wmpNRocjm4kxfaL2tgQn0yj2i21M/edit?usp=sharing

need to work on the summary so any pointers for that would be greatly appreciated!

**Comment by ktrammell95** [comment]
Tips:
1. You don't have to give your full address unless you really want to
2. LinkedIn and GitHub can be listed as the following if you want as long as you make them clickable
LinkedIn: joe-baranski
GitHub: ejbee3
3. For skills you don't have to say what each does or is for, just list HTML, CSS, etc... Also don't forget Git, GitHub, Slack, Trello ... etc
4. Think about adding links for your projects so people can see your code if they want to
5. I might be weird but I actually like "with a focus on economics, the environment, education, and animal welfare."

**Comment by ktrammell95** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBVZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--978506c32fc72f81eabd7234e584cda7e38900af/giphy-6.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/71)**__
