### ISSUE TITLE
week 06 - day 02  - choose your own adventure

### ISSUE THREAD

**Issue by mdewey** [ejbee3/assignments#22]
# Choose your own API Adventure

In this assignment, you'll build a front end for an API of your choice

## Objectives

- Reinforce component architecture in React
- Reinforce reading of API documentation (some are great, and some are terrible)
- Creating and designing your own features for a web app

## Requirements

We're going to build a front end for an API of your choice. Choose one from [this list](https://github.com/toddmotto/public-apis) or an API that you are aware of. 

_NOTE_ You'll need to choose one with `Auth` being `No` or `apiKey` since we haven't covered `OAuth` authentication yet.

_NOTE_ You'll also need to check to see if the API will work from your browser. You can do a quick check by making a small `app-app`, doing an `axios.get` or `fetch` of one API URL and see if you get browser errors.

### Explorer Mode

- [x] Select an API and get it approved by your instructor.
- [x] Read your API docs
- [x] Use Postman to make some API requests to be familiar with the API and the data it returns
- [ ] Create a list of the features you are going to create and how they will work
- [ ] Design your User Interface
- [ ] Design your HTML statically in `App.js`
- [ ] Make it dynamic
- [ ] Use components when needed
- [ ] Deploy it and share it with friends

### Adventure Mode

- [ ] Add multiple pages to your site.
- [ ] Add a second API
- [ ] Work on components and clean, well-commented code.
- [ ] Work on other assignments you might be assigned as well. Career support or old adventure modes come to mind.
- [ ][do you wanna build a snowman?] (https://suncoast.io/handbook/curriculum/front-end/react-ii/assignments/snowman)

### Epic mode
- [ ] Capstones are going to be coming sooner rather than later. Check out [this resource](https://suncoast.io/handbook/curriculum/final-project/project-ideas/) To help get you started.

**Comment by ejbee3** [comment]
I want to use an API that allows posting and deleting so I'm going to redo this assignment using the CatAPI which takes cat images from tumblr. It has voting features which are posts and deletes and you can also favorite and add images by posting which will give me a better understanding of how APIs work so I can learn how to make my own and never have to use one again.

Also, leaving this open and closing it when I remake it using the cat API.

**Comment by ejbee3** [comment]
https://github.com/ejbee3/choose-your-adventure

I'm not done with this.
If I get time when I finish the weekend assignment, I'll work on this. I want to display cat images based on the category dropdown box. I can't get the category items to display yet but I need to start working on the homework because you said so to Hector and I listen in class.

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBXUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bceeb145d881263a0f2f05f92594ddf64d6d8c0a/giphy-13.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/78)**__
