### ISSUE TITLE
capstone 02 - let's get visual

### ISSUE THREAD

**Issue by mdewey** [ejbee3/assignments#31]
# Let's get visual!

With the wireframes created, we need to start breathing life into our application. The next step would be to create HTML & CSS. This is the next step because, remember, it all comes down to HTML. This is what the user sees

_NOTE_: Really take advantage of this weekend to get make progress on your capstone. Like the last 7 weeks, the next 5 weeks will go by _fast_.

## Objectives

- Create the HTML and CSS for the final project

## Requirements

- Using `app-app`, start implementing your HTML

### Explorer Mode

- [ ] Create the HTML and CSS version of your wireframes. Stay as true as possible. This should focus on static HTML and CSS.

**Comment by ejbee3** [comment]
I'm leaving this here as just an ongoing idea log. I think I want to tailor my app to high schoolers. Pretty much every high school kid has a phone so I'm going to make a mobile student portal when students can interact with teachers, maybe make a kind of four square function where they can check into say a high school class or the cafeteria for lunch (but not have the app track them constantly). It could also be effective in emergencies if there was a central place to meet and students could check into that location to make sure they are okay. This would be in the teacher portal though.

**Comment by ejbee3** [comment]
https://www.figma.com/file/DUQ7mqh7b8XmuM7vyOcCR6h2/New-Capstone?node-id=0%3A1

I made a new wireframe. I'm working on the HTML and CSS now making it look like the mock up. I'm using the FourSquare API for the location tracking. This is a much tighter, cohesive idea to me and I'm much more excited about it than my previous capstone idea.

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Ring that bell!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBTQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fabcecd7c921cc4014bfcce0bd127f9e89ef3986/meets-2.gif)
> &ldquo;Ring that bell!&rdquo;
__&mdash; via **[Mark Dewey](https://gifs.suncoast.io/venerations/62)**__
